language: ruby
rvm:
  - 2.0
  - 2.2
script:
  - bundle exec rspec -c -fd
addons:
    code_climate:
        repo_token: '${CODECLIMATE_REPO_TOKEN}'
after_success:
  - bundle exec codeclimate-test-reporter

